class InterestCategory {
  final String name;
  final String emoji;
  final List<String> subcategories;

  const InterestCategory({
    required this.name,
    required this.emoji,
    required this.subcategories,
  });
}

const List<InterestCategory> interestCategories = [
  InterestCategory(
    name: 'Sports',
    emoji: '⚽',
    subcategories: [
      'Football',
      'Basketball',
      'Tennis',
      'Swimming',
      'Running',
      'Cycling',
      'Gym',
      'Yoga',
      'Boxing',
      'Rugby',
      'Cricket',
      'Badminton',
      'Volleyball',
      'Golf',
      'Climbing',
    ],
  ),
  InterestCategory(
    name: 'Arts & Crafts',
    emoji: '🎨',
    subcategories: [
      'Crochet',
      'Knitting',
      'Painting',
      'Drawing',
      'Sculpting',
      'Photography',
      'Pottery',
      'Embroidery',
      'Origami',
      'Jewellery Making',
      'Candle Making',
      'Sewing',
    ],
  ),
  InterestCategory(
    name: 'Music',
    emoji: '🎵',
    subcategories: [
      'Guitar',
      'Piano',
      'Drums',
      'Violin',
      'Singing',
      'DJing',
      'Bass',
      'Songwriting',
      'Choir',
      'Jazz',
      'Classical',
      'Rock',
      'Pop',
    ],
  ),
  InterestCategory(
    name: 'Gaming',
    emoji: '🎮',
    subcategories: [
      'Video Games',
      'Board Games',
      'Card Games',
      'Tabletop RPG',
      'Esports',
      'Chess',
    ],
  ),
  InterestCategory(
    name: 'Food & Drink',
    emoji: '🍕',
    subcategories: ['Cooking', 'Baking', 'Coffee', 'Wine Tasting', 'Cocktails'],
  ),
  InterestCategory(
    name: 'Outdoors',
    emoji: '🌿',
    subcategories: [
      'Hiking',
      'Camping',
      'Surfing',
      'Skateboarding',
      'Gardening',
      'Bird Watching',
      'Fishing',
      'Rock Climbing',
      'Kayaking',
    ],
  ),
  InterestCategory(
    name: 'Film & TV',
    emoji: '🎬',
    subcategories: [
      'Filmmaking',
      'Screenwriting',
      'Anime',
      'Documentaries',
      'Horror',
      'Sci-Fi',
      'Comedy',
      'Drama',
      'Animation',
      'Cinema',
    ],
  ),
  InterestCategory(
    name: 'Reading & Writing',
    emoji: '📚',
    subcategories: [
      'Fiction',
      'Non-Fiction',
      'Poetry',
      'Journalism',
      'Blogging',
      'Fantasy',
      'Sci-Fi',
      'Classics',
      'Self-Help',
      'History',
      'Philosophy',
    ],
  ),
  InterestCategory(
    name: 'Social & Lifestyle',
    emoji: '🌍',
    subcategories: [
      'Travel',
      'Volunteering',
      'Fashion',
      'Journaling',
      'Languages',
      'Dancing',
      'Clubbing',
    ],
  ),
];
