// ── All London Boroughs ─────────────────────────────────────────────────────
const List<String> londonBoroughs = [
  'Barking and Dagenham',
  'Barnet',
  'Bexley',
  'Brent',
  'Bromley',
  'Camden',
  'City of London',
  'Croydon',
  'Ealing',
  'Enfield',
  'Greenwich',
  'Hackney',
  'Hammersmith and Fulham',
  'Haringey',
  'Harrow',
  'Havering',
  'Hillingdon',
  'Hounslow',
  'Islington',
  'Kensington and Chelsea',
  'Kingston upon Thames',
  'Lambeth',
  'Lewisham',
  'Merton',
  'Newham',
  'Redbridge',
  'Richmond upon Thames',
  'Southwark',
  'Sutton',
  'Tower Hamlets',
  'Waltham Forest',
  'Wandsworth',
  'Westminster',
];

// ── Year group options ─────────────────────────────────────────────────────
const List<String> yearGroups = [
  'Year 1',
  'Year 2',
  'Year 3',
  'Year 4',
  'Year 5',
  'Year 6',
  'Masters',
  'PhD',
];

// ── All London Universities ────────────────────────────────────────────────
const List<String> londonUniversities = [
  'Birkbeck, University of London',
  'Brunel University London',
  'City, University of London',
  'Courtauld Institute of Art',
  'Goldsmiths, University of London',
  'Guildhall School of Music & Drama',
  'Imperial College London',
  'Institute of Cancer Research',
  'King\'s College London',
  'Kingston University',
  'London Business School',
  'London Metropolitan University',
  'London School of Economics and Political Science',
  'London School of Hygiene & Tropical Medicine',
  'London South Bank University',
  'Middlesex University',
  'Queen Mary University of London',
  'Queen\'s University Belfast (London Campus)',
  'Ravensbourne University London',
  'Royal Academy of Music',
  'Royal College of Art',
  'Royal College of Music',
  'Royal Holloway, University of London',
  'Royal Veterinary College',
  'School of Oriental and African Studies',
  'St George\'s, University of London',
  'The University of Law (London)',
  'Trinity Laban Conservatoire of Music and Dance',
  'University College London',
  'University of East London',
  'University of Greenwich',
  'University of London',
  'University of Roehampton',
  'University of the Arts London',
  'University of Westminster',
  'Wrexham University (London Campus)',
];
