name: Flutter CI/CD

# Run pipeline on pushes to any branch or pull requests to main
on:
  push:
    branches: 
        - '*'
  pull_request:
    branches: 
        - main

jobs:
  # BUILD JOB FOR ANDROID
  build_android:
    runs-on: ubuntu-latest
    env:
        FLUTTER_CHANNEL: 'stable'

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up the Java environment 
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true 
        pub-cache: true

    # Install dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Format code
    - name: Run Linter
      run: flutter analyze

    # Run Tests
    - name: Run Tests
      run: flutter test

    # Build the APK if in the main branch
    - name: Build APK
      if: github.ref == 'refs/heads/main'
      run: flutter build apk --debug
    
    # Upload APK artifact
    - name: Upload APK Artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

  # BUILD JOB FOR IOS
  build_ios:
    runs-on: macos-latest
    env:
        FLUTTER_CHANNEL: 'stable'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby & CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true 
        pub-cache: true

    - name: Install Dependencies
      run: flutter pub get

    - name: Build iOS App
      if: github.ref == 'refs/heads/main'
      run: flutter build ios --debug --no-codesign

    - name: Zip iOS Build
      if: github.ref == 'refs/heads/main'
      run: |
        cd build/ios/iphoneos
        zip -r MyFlutterApp.zip Runner.app

    - name: Upload iOS Artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: ios-debug-app
        path: build/ios/iphoneos/MyFlutterApp.zip